/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ControladorJuego;
import View.GUIJuego;

/**
 *
 * @author abiga
 */
public class GUIInicio extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(GUIInicio.class.getName());

    /**
     * Creates new form GUIInicio
     */
    public GUIInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel2 = new javax.swing.JLabel();
        Jugar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        comboColor = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccion de color ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, -1, -1));

        Jugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/boton.png"))); // NOI18N
        Jugar.setContentAreaFilled(false);
        Jugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart(evt);
            }
        });
        getContentPane().add(Jugar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 150, -1, -1));

        jButton2.setBackground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Historia");
        jButton2.setPreferredSize(new java.awt.Dimension(1, 27));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistoria(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 180, 40));

        jButton3.setBackground(new java.awt.Color(51, 51, 255));
        jButton3.setText("Creditos");
        jButton3.setPreferredSize(new java.awt.Dimension(1, 27));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreditos(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 120, 40));

        jButton4.setBackground(new java.awt.Color(51, 51, 255));
        jButton4.setText("Instrucciones");
        jButton4.setPreferredSize(new java.awt.Dimension(1, 27));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInstrucciones(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, 160, 40));

        comboColor.setBackground(new java.awt.Color(51, 51, 255));
        comboColor.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        comboColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Amarillo", "Azul", "Verder" }));
        comboColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboColorActionPerformed(evt);
            }
        });
        getContentPane().add(comboColor, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgInicio_1.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHistoria(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistoria
        GUIHistoria demo = new GUIHistoria();
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnHistoria

    private void btnInstrucciones(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInstrucciones
        GUIInstrucciones demo = new GUIInstrucciones();
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnInstrucciones

    private void btnCreditos(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreditos
        GUICreditos demo = new GUICreditos();
        demo.setVisible(true);
        demo.setLocationRelativeTo(null);

    }//GEN-LAST:event_btnCreditos

    private void btnStart(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart
//        GUIJuego demo = new GUIJuego ();
//        demo.setVisible(true);
//        demo.setLocationRelativeTo(null);
//        
//        int idCombo = comboColor.getSelectedIndex();
//        int colorId = 0;
//                if (idCombo == 0){
//                    colorId = 0;//rojo
//                }else if (idCombo == 1){
//                    colorId = 1;//Amarillo
//                }//Los colores que faltan
//                new Controller.ControladorJuego (demo.getPanelControl1(), demo.getPanelTablero1(), colorId);
//                this.setVisible(false);

        int idCombo = comboColor.getSelectedIndex();
        int colorId = 0;

        if (idCombo == 0) {
            colorId = 0;
        }//fin if
        else if (idCombo == 1) {
            colorId = 1;
        }//fin if
        else if (idCombo == 2) {
            colorId = 2;
        }//fin if
        else if (idCombo == 3) {
            colorId = 3;
        }//fin if

        ControladorJuego control = new ControladorJuego(colorId);
        GUIJuego juego = new GUIJuego();
        juego.setVisible(true);
        juego.setLocationRelativeTo(null);
//        new controller.ControladorJuego(juego.getPanelControl1(), juego.getPanelTablero1(), colorId);
        this.setVisible(false);
    }//GEN-LAST:event_btnStart

    private void comboColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboColorActionPerformed

    }//GEN-LAST:event_comboColorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jugar;
    private javax.swing.JComboBox<String> comboColor;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
