/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author abiga
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }

    public JButton getBtnDado() {
        return btnDado;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }

    public void setTxtNumeroDado(int Numero) {
        this.txtNumeroDado.setText("Resultado Dado: " + Numero);
    }

    public void setTxtTurnoJugador(String txtTurno) {
        txtTurnoJugador.setText("Turno Juagdor: " + txtTurno);
    }

    public JLabel getTxtTiempo() {
        return txtTiempo;
    }
//Set para el label del tiempo 

    public void setTxtTiempo(int valor) {
        txtTiempo.setText("Tiempo:" + valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroDado = new javax.swing.JLabel();
        txtTurnoJugador = new javax.swing.JLabel();
        btnDado = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        txtTiempo = new javax.swing.JLabel();
        txtPuntosJugador = new javax.swing.JLabel();
        txtPuntosOponente = new javax.swing.JLabel();

        txtNumeroDado.setText("Número Dado");

        txtTurnoJugador.setText("Turno Jugador");

        btnDado.setText("Dado");

        btnReinicio.setText("Reinicio");

        btnMenu.setText("Menú");

        txtTiempo.setText("Tiempo:");

        txtPuntosJugador.setText("Puntos J:");

        txtPuntosOponente.setText("Puntos O:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnDado)
                            .addComponent(btnMenu)
                            .addComponent(btnReinicio)
                            .addComponent(txtTurnoJugador)
                            .addComponent(txtNumeroDado)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txtTiempo)
                        .addGap(32, 32, 32)
                        .addComponent(txtPuntosJugador)
                        .addGap(46, 46, 46)
                        .addComponent(txtPuntosOponente)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(btnDado)
                .addGap(48, 48, 48)
                .addComponent(txtNumeroDado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTurnoJugador)
                .addGap(36, 36, 36)
                .addComponent(btnReinicio)
                .addGap(37, 37, 37)
                .addComponent(btnMenu)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTiempo)
                    .addComponent(txtPuntosJugador)
                    .addComponent(txtPuntosOponente))
                .addContainerGap(22, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel txtNumeroDado;
    private javax.swing.JLabel txtPuntosJugador;
    private javax.swing.JLabel txtPuntosOponente;
    private javax.swing.JLabel txtTiempo;
    private javax.swing.JLabel txtTurnoJugador;
    // End of variables declaration//GEN-END:variables
}
