/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author abiga
 */
public class PanelControl extends javax.swing.JPanel {

    /**
     * Creates new form PanelControl
     */
    public PanelControl() {
        initComponents();
    }

    public JButton getBtnDado() {
        return btnDado;
    }

    public JButton getBtnReinicio() {
        return btnReinicio;
    }

    public void setTxtNumeroDado(int Numero) {
        this.txtNumeroDado.setText("Resultado Dado: " + Numero);
    }

    public void setTxtTurnoJugador(String txtTurno) {
        txtTurnoJugador.setText("Turno Juagador: " + txtTurno);
    }

    public JLabel getTxtTiempo() {
        return txtTiempo;
    }
//Set para el label del tiempo 

    public void setTxtTiempo(int valor) {
        txtTiempo.setText("Tiempo:" + valor);
    }

    public JLabel getTxtPuntosJugador() {
        return txtPuntosJugador;
    }

    public void setTxtPuntosJugador(int valor) {
        txtPuntosJugador.setText("Puntos de Jugador:" + valor);
    }

    public JLabel getTxtPuntosOponente() {
        return txtPuntosOponente;
    }

    public void setTxtPuntosOponente(int valor) {
        txtPuntosOponente.setText("Puntos de Oponente:" + valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtNumeroDado = new javax.swing.JLabel();
        txtTurnoJugador = new javax.swing.JLabel();
        btnDado = new javax.swing.JButton();
        btnReinicio = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        txtTiempo = new javax.swing.JLabel();
        txtPuntosJugador = new javax.swing.JLabel();
        txtPuntosOponente = new javax.swing.JLabel();

        txtNumeroDado.setText("Número Dado");

        txtTurnoJugador.setText("Turno Jugador");

        btnDado.setText("Dado");

        btnReinicio.setText("Reinicio");

        btnMenu.setText("Menú");

        txtTiempo.setText("Tiempo:");

        txtPuntosJugador.setText("Puntos J:");

        txtPuntosOponente.setText("Puntos O:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addComponent(btnDado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNumeroDado)
                            .addComponent(btnReinicio))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnMenu, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtTurnoJugador, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(txtTiempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(txtPuntosJugador)
                        .addGap(54, 54, 54)
                        .addComponent(txtPuntosOponente)))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnDado)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroDado)
                    .addComponent(txtTurnoJugador))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReinicio)
                    .addComponent(btnMenu))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPuntosOponente)
                    .addComponent(txtPuntosJugador)
                    .addComponent(txtTiempo))
                .addContainerGap(40, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDado;
    private javax.swing.JButton btnMenu;
    private javax.swing.JButton btnReinicio;
    private javax.swing.JLabel txtNumeroDado;
    private javax.swing.JLabel txtPuntosJugador;
    private javax.swing.JLabel txtPuntosOponente;
    private javax.swing.JLabel txtTiempo;
    private javax.swing.JLabel txtTurnoJugador;
    // End of variables declaration//GEN-END:variables
}
