package View;
import java.awt. Point;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;



/**
 *
 * @author abiga
 */
public class PanelTablero extends javax.swing.JPanel 
{

    /**
     * Creates new form PanelTablero
     */
    public PanelTablero() {
        initComponents();
        this.addMouseListener(new MouseAdapter() {
            @Override
            //MouseEvent
            public void mousePressed(MouseEvent e) {
                Point p = e.getPoint();
                moverFicha(p);
            }
        });}
    public void moverFicha(Point p){
        //Clase point
        imgFicha.setLocation(p);
        System.out.println("Coordenadas : " + p.x + " , " + p.y);
    }//fin del metodo moverFicha
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        imgFicha = new javax.swing.JLabel();
        imgFicha2 = new javax.swing.JLabel();
        imgFicha3 = new javax.swing.JLabel();
        imgFicha4 = new javax.swing.JLabel();
        imgTablero = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgFicha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FichaRoja.png"))); // NOI18N
        add(imgFicha, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        imgFicha2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FichaAzul.png"))); // NOI18N
        add(imgFicha2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, -1, -1));

        imgFicha3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FichaAmarilla.png"))); // NOI18N
        add(imgFicha3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        imgFicha4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FichaVerde.png"))); // NOI18N
        add(imgFicha4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));

        imgTablero.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tablerografico.png"))); // NOI18N
        add(imgTablero, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel imgFicha;
    private javax.swing.JLabel imgFicha2;
    private javax.swing.JLabel imgFicha3;
    private javax.swing.JLabel imgFicha4;
    private javax.swing.JLabel imgTablero;
    // End of variables declaration//GEN-END:variables
}
